version: "3.9"

services:
  user-service:
    build: ./Microservices/user-service
    container_name: user-service
    ports:
      - "3000:3000"

  product-service:
    build: ./Microservices/product-service
    container_name: product-service
    ports:
      - "3001:3001"

  order-service:
    build: ./Microservices/order-service
    container_name: order-service
    ports:
      - "3002:3002"

  gateway-service:
    build: ./Microservices/gateway-service
    container_name: gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
      
